In [22]:
import pandas as pd
import numpy as np

In [23]:
data ={
    'Student_Id':[1,2,3,4,5,6,7,8,9,10],
    'Name':['A','B','C','D','E','F',np.nan,'H','I','J'],
    'Maths':[54,90,55,88,66,np.nan,66,120,np.nan,58],
    'Science':[88,np.nan,75,85,44,55,74,110,80,77],
    'English':[78,99,65,33,np.nan,56,45,155,38,77],
    'Attendances':[90,95,85,np.nan,98,105,70,88,91,96]
}

In [24]:
df= pd.DataFrame(data)
df

   Student_Id Name  Maths  Science  English  Attendances
0           1    A   54.0     88.0     78.0         90.0
1           2    B   90.0      NaN     99.0         95.0
2           3    C   55.0     75.0     65.0         85.0
3           4    D   88.0     85.0     33.0          NaN
4           5    E   66.0     44.0      NaN         98.0
5           6    F    NaN     55.0     56.0        105.0
6           7  NaN   66.0     74.0     45.0         70.0
7           8    H  120.0    110.0    155.0         88.0
8           9    I    NaN     80.0     38.0         91.0
9          10    J   58.0     77.0     77.0         96.0

In [25]:
df.isnull().sum()

Student_Id     0
Name           1
Maths          2
Science        1
English        1
Attendances    1
dtype: int64

In [26]:
df['Maths'] = df['Maths'].fillna(df['Maths'].mean()).astype(int)
df['English'] = df['English'].fillna(df['English'].mean()).astype(int)
df['Science'] = df['Science'].fillna(df['Science'].mean()).astype(int)
df['Attendances'] = df['Attendances'].fillna(df['Attendances'].mean()).astype(int)
df['Name'] = df['Name'].fillna(df['Name'].mode()[0])

In [7]:
# df['Maths'] = df['Maths'].clip(0,100)
# df['Science'] = df['Science'].clip(0,100)
# df['English'] = df['English'].clip(0,100)
# df['Attendances'] = df['Attendances'].clip(0,100)

In [27]:
df

   Student_Id Name  Maths  Science  English  Attendances
0           1    A     54       88       78           90
1           2    B     90       76       99           95
2           3    C     55       75       65           85
3           4    D     88       85       33           90
4           5    E     66       44       71           98
5           6    F     74       55       56          105
6           7    A     66       74       45           70
7           8    H    120      110      155           88
8           9    I     74       80       38           91
9          10    J     58       77       77           96

In [28]:
df.loc[2,'Maths'] = 500

In [29]:
df

   Student_Id Name  Maths  Science  English  Attendances
0           1    A     54       88       78           90
1           2    B     90       76       99           95
2           3    C    500       75       65           85
3           4    D     88       85       33           90
4           5    E     66       44       71           98
5           6    F     74       55       56          105
6           7    A     66       74       45           70
7           8    H    120      110      155           88
8           9    I     74       80       38           91
9          10    J     58       77       77           96

In [30]:
cols = ['Maths','English','Science','Attendances']
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3-Q1
    lower = Q1 - 1.5*IQR
    upper = Q3 + 1.5*IQR
    outlier = df[(df[col]<lower) | (df[col] > upper)]
    len(outlier)
    # print(lower,upper)
    
    # handel outlier 
    df[col]= np.where(df[col]<lower,lower,
                  np.where(df[col]>upper,upper,df[col]))

In [31]:
df

   Student_Id Name   Maths  Science  English  Attendances
0           1    A   54.00     88.0    78.00       90.000
1           2    B   90.00     76.0    99.00       95.000
2           3    C  124.75     75.0    65.00       85.000
3           4    D   88.00     85.0    33.00       90.000
4           5    E   66.00     60.0    71.00       98.000
5           6    F   74.00     60.0    56.00      105.000
6           7    A   66.00     74.0    45.00       77.625
7           8    H  120.00     98.0   122.75       88.000
8           9    I   74.00     80.0    38.00       91.000
9          10    J   58.00     77.0    77.00       96.000

In [32]:
df['Mths_log'] = np.log(df['Maths'])
df['English_log'] = np.log(df['English'])

In [33]:
df

,Student_Id,Name,Maths,Science,English,Attendances,Mths_log,English_log
0,1,A,54.00,88.0,78.00,90.000,3.988984,4.356709
1,2,B,90.00,76.0,99.00,95.000,4.499810,4.595120
2,3,C,124.75,75.0,65.00,85.000,4.826312,4.174387
3,4,D,88.00,85.0,33.00,90.000,4.477337,3.496508
4,5,E,66.00,60.0,71.00,98.000,4.189655,4.262680
5,6,F,74.00,60.0,56.00,105.000,4.304065,4.025352
6,7,A,66.00,74.0,45.00,77.625,4.189655,3.806662
7,8,H,120.00,98.0,122.75,88.000,4.787492,4.810150
8,9,I,74.00,80.0,38.00,91.000,4.304065,3.637586
9,10,J,58.00,77.0,77.00,96.000,4.060443,4.343805